name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TZ: Europe/Paris

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        date=$(date +%s)
        day=$(date -d "@$date" +%Y-%m-%d)
        discr=$(date -d "@$date" "+(%H*60+%M)*60+%S" | bc)
        docker build . --file Dockerfile --tag bot.cancelinator:$day.$discr
